<a href="https://colab.research.google.com/github/jc7qx/classMaterial/blob/master/numpyIntro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy

Numpy是一個python數值計算套件，提供向量、矩陣計算，包括多維矩陣。並能處理大型資料集。主要的特點如下
- N 維陣列資料結構核心 ndarray
- 陣列儲存於連續記憶體具快速計算效能
- 針對不同型態陣列矩陣提供基礎計算能力
- 利用python語言特性使計算資料向量化
- 提供線性代數各項計算函數

#### 建立陣列矩陣

In [1]:
# pip install numpy

In [3]:
import numpy as np
x = np.array([1, 2, 3])
y = np.array([[1,2], [3,4]])
z = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(x)
print(y)
print(z)

[1 2 3]
[[1 2]
 [3 4]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [4]:
a1_zeros = np.zeros((3,3))
a2_ones = np.ones((2,2))
a3_range = np.arange(0, 10, 2)
print(a1_zeros)
print(a2_ones)
print(a3_range)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[0 2 4 6 8]


#### numpy資料存取

In [5]:
arr1d = np.array([10, 20, 30, 40, 50])
arr1d[2]

30

In [6]:
arr1d[-1]

50

In [7]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
arr2d[1,1]

5

In [11]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr[1:4] #elements from index 1 to 3

array([[4, 5, 6]])

In [12]:
arr[:, 1]

array([2, 5])

In [13]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

In [14]:
np.array([1,3,5])

array([1, 3, 5])

In [17]:
arr[np.array([1,3,5])]

array([20, 40, 60])

In [20]:
arr[arr%3==0]

array([30, 60, 90])

#### numpy 基本函數

In [21]:
a = np.array([0, np.pi/2, np.pi])
print ("Sine values of array elements:", np.sin(a))

Sine values of array elements: [0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [22]:
a = np.array([0, 1, 2, 3])
print ("Exponent of array elements:", np.exp(a))

Exponent of array elements: [ 1.          2.71828183  7.3890561  20.08553692]


In [23]:
print ("Square root of array elements:", np.sqrt(a))

Square root of array elements: [0.         1.         1.41421356 1.73205081]


#### 線性代數運算

In [25]:
#向量相加
a = np.array([1,2])
b = np.array([3,0])
a+b

array([4, 2])

In [28]:
#建立矩陣
A = np.array([[6,1,1],[4,-2,5],[2,8,7]])
A

array([[ 6,  1,  1],
       [ 4, -2,  5],
       [ 2,  8,  7]])

In [29]:
#矩陣rank
np.linalg.matrix_rank(A)

3

In [30]:
#trace
np.trace(A)

11

In [31]:
#矩陣determinant
np.linalg.det(A)

-306.0

In [32]:
#反矩陣
np.linalg.inv(A)

array([[ 0.17647059, -0.00326797, -0.02287582],
       [ 0.05882353, -0.13071895,  0.08496732],
       [-0.11764706,  0.1503268 ,  0.05228758]])

In [35]:
# eigh values and vectors
B = np.array([[1, 2j],[2j, 5]])
a, v = np.linalg.eigh(B)
print(a,"\n", v)

[0.17157288 5.82842712] 
 [[-0.92387953+0.j         -0.38268343+0.j        ]
 [ 0.        +0.38268343j  0.        -0.92387953j]]


In [36]:
#對角矩陣
a = np.diag((1,2,3))

In [37]:
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [38]:
a, v = np.linalg.eig(a)

In [39]:
print(a, "\n", v)

[1. 2. 3.] 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 統計函數

In [5]:
data = [5, 6, 7, 8, 9, 10, 11, 20, 30]
mean_estimate = np.mean(data)
median_estimate = np.median(data)
population_variance = np.var(data, ddof=0)
sample_variance = np.var(data, ddof=1)
population_std_dev = np.std(data, ddof=0)
sample_std_dev = np.std(data, ddof=1)

In [8]:
print(sample_std_dev)

8.120618476719889


In [9]:
cv = sample_std_dev/mean_estimate
signal_noise_ratio = 1/cv

In [10]:
print(signal_noise_ratio)

1.4503547742751612


In [12]:
p75_w_percentile = np.percentile(list(np.arange(7, 35, 1)), q=75, interpolation='linear')
p75_w_quantile = np.quantile(list(np.arange(7, 35, 1)), q=0.75, interpolation='linear')

In [14]:
even_sample=list(np.arange(7, 35, 1))

In [ ]:
p25 = np.percentile(data_sample_even, q=25, interpolation='linear')
p75 = np.percentile(data_sample_even, q=75, interpolation='linear')
iqr = p75 - p25

In [ ]:
min_value = np.min(data)
max_value = np.max(data)