# Numpy 介紹

NumPy 是 Python 中一個強大的**數值計算套件庫**，它具有以下特點
1. 高效率的多維陣列和矩陣運算：NumPy 提供了高效的多維陣列和矩陣運算功能，能夠快速處理大規模的數據計算。
2. 快速運算速度：NumPy 的底層使用 C 語言編寫，能夠跳過 Python 的全域解譯器鎖（GIL），因此運算速度遠超過純 Python 代碼。
3. 支持向量化運算：NumPy 支持向量化運算，可以在單一指令下對整個陣列進行操作，減少了循環的需要。
4. 與其他庫的整合：NumPy 可以與其他 Python 科學計算庫（如 Pandas、SciPy、Matplotlib 等）整合，提供全面性的數據分析和科學計算功能。

NumPy 能夠高效地計算大量數據，尤其是在科學計算和數據分析領域。相比於 Python 原生的列表(L)，NumPy 的陣列（ndarray）在存儲和運算效率上有明顯優勢，NumPy 擅長解決的計算問題包括
1. 大規模數據處理：NumPy 可以快速高效地處理大量數據，適合於機器學習和深度學習等領域。
2. 多維陣列和矩陣運算：NumPy 提供了豐富的多維陣列和矩陣運算功能，適合於線性代數和矩陣計算。
3. 科學計算和數學建模：NumPy 提供了大量的數學函數和運算工具，適合於科學計算和數學建模. 

根據 numpy 的數值計算能力，非常適合在以下的應用中使用 numpy 來處理數據計算的問題
1. 數值計算和數據分析
    - 科學研究和工程：NumPy 在科學研究和工程領域中被廣泛用於數值計算和數據分析，尤其是在物理、化學和生物學等領域。
    - 機器學習和數據科學：NumPy 是機器學習和數據科學的基礎庫，常用於數據預處理和算法實現。
2. 信號處理
    - NumPy 在信號處理中被用於過濾、Fourier 分析和時間域分析等任務。
3. 圖像處理
    - NumPy 用於圖像處理任務，如過濾、變換和控圖像數據。
4. 模擬和建模
    - 科學模擬：NumPy 用於物理、化學和生物學等領域的模擬和建模。
    - 金融和經濟建模：NumPy 用於風險分析、期權定價和經濟建模。
5. 其他領域
    - 天文學：NumPy 用於處理和控天文數據，如望遠鏡圖像或光譜。
    - 生物信息學：NumPy 用於分析基因數據、蛋白質結構預測和計算生物學。
    - 遊戲開發：NumPy 用於物理模擬、碰撞檢測和處理大型數據集。
6. 教育和研究
    - NumPy 在教育和研究環境中被廣泛用於教學和實驗。

接下來的課程，先介紹 numpy 的基本操作及有用的函數，再來展示二個可以運用 numpy 來處理的技術，即影像基礎處理與線性回歸模型基礎矩陣運算。 

## Numpy 基礎

### numpy array

numpy 的核心為 numpy arrays, 它是一個固定大小的資料容器，執行效能優於 python 原生的 List 及 Tuple 資料結構。
- numpy array 只能儲存單一資料型別的資料，複合型的資料型別資料必須儲存於物件資料型別。 numpy array 可以是一維或多維陣列。資料表類型的資料可以利用 numpy 的多為陣列表示，一維的 numpy array 可以視為 python list，**但記住 numpy array 只能儲存單一資料型別的資料**。

### 使用 numpy 的功能，先導入 numpy 套件

In [ ]:
import numpy as np #為簡化使用，導入 numpy 後設定簡稱 np

### 建立陣列

In [9]:
x = np.array(1)
print(type(x))

<class 'numpy.ndarray'>


In [4]:
#建立一維陣列
x = np.array([1, 2, 3, 4, 5])
print(type(x))

<class 'numpy.ndarray'>


In [ ]:
# 建立二維矩陣
y = np.array([[11, 22, 33], [99, 77, 55]])
print(y)

[[11 22 33]
 [99 77 55]]


In [ ]:
y.shape # 維度為 2x3 , 2 row 3 column

(2, 3)

In [ ]:
# 建立三維矩陣
z = np.array([[[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]], [[5, 4, 3, 2, 1],[1, 3, 5, 7, 9]]])
print(z)
print(z.shape)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[ 5  4  3  2  1]
  [ 1  3  5  7  9]]]
(2, 2, 5)


In [8]:
# array.ndim：查看矩陣的維度
print(x.ndim)
print(y.ndim)
print(z.ndim)

1
2
3


In [11]:
# ndmin：可以用來決定建立的矩陣維度
x = np.array([1, 2, 3, 4, 5, 6], ndmin=2)
print(x)
print(x.ndim)

[[1 2 3 4 5 6]]
2


In [13]:
# 建立一個 4x5 全為 0 的矩陣
np.zeros([4,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
# 建立一個 3x3 全為 1 的矩陣
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# 建立一個 1 開始，最大到 10 一次加 2 的陣列
np.arange(1,10, 2)

array([1, 3, 5, 7, 9])

In [ ]:
# 建立一個 0 到 6 平均分成 3 份的矩陣 [0 3 6]
np.linspace(0, 6, 3) 

array([0., 3., 6.])

In [17]:
# 建立一個 2x3 的矩陣，裡面的元素全都去 5
np.full([2,3], 5)

array([[5, 5, 5],
       [5, 5, 5]])

In [18]:
# 建立一個 3x3 的單位矩陣
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
# 建立 2x3 的矩陣，元素的值為隨機的
np.random.random([3,3])

array([[0.93658791, 0.27537065, 0.2098625 ],
       [0.3994192 , 0.90162593, 0.42288799],
       [0.81686638, 0.79586098, 0.89892919]])

## numpy 運算

In [23]:
# 矩陣轉置
m1 = np.array([[1,2, 3], [4, 5, 6], [7, 8, 9]])
print(m1)
m1_T = m1.T
print(m1_T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [24]:
# 矩陣加、減、乘、除
m1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
m2 = np.array([[1,5,9],[7,5,3],[4,5,6]])

In [25]:
print(m1+m2)

[[ 2  7 12]
 [11 10  9]
 [11 13 15]]


In [26]:
print(m1-m2)

[[ 0 -3 -6]
 [-3  0  3]
 [ 3  3  3]]


In [27]:
print(m1*m2)

[[ 1 10 27]
 [28 25 18]
 [28 40 54]]


In [28]:
print(m1/m2)

[[1.         0.4        0.33333333]
 [0.57142857 1.         2.        ]
 [1.75       1.6        1.5       ]]


In [29]:
# 矩陣內積
print(np.dot(m1, m2))

[[ 27  30  33]
 [ 63  75  87]
 [ 99 120 141]]


In [30]:
print(np.dot(m2, m1))

[[ 84  99 114]
 [ 48  63  78]
 [ 66  81  96]]


In [ ]:
# 矩陣廣播
m3 = m1+1 #將1x1廣播成3x3的ones
print(m3)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [32]:
m33 = m1 + np.ones(3)
print(m33)

[[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]


In [33]:
m4 = m1 + np.array([5, 5, 5])
print(m4)

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


### 矩陣切割

In [ ]:
# [start:end:step]
a1 = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(a1[1:5])

[2 3 4 5]


In [36]:
m = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(m)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [38]:
print(m[1, 1:4])

[7 8 9]


In [39]:
print(m[0:2, 1:3])

[[2 3]
 [7 8]]


### 矩陣複製
- .copy():複製一個一樣的陣列給 x，這時若改變 x，並不會對原本的陣列造成影響
- .view():用來指到一個陣列 y，若 y 改變內容，原本的陣列也會改變

In [41]:
a1 = np.array([1, 2, 3, 4, 5])
p = a1.copy()
p[3]=99
print("a1 = ", a1)
print("p = ", p)

a1 =  [1 2 3 4 5]
p =  [ 1  2  3 99  5]


In [42]:
a2 = np.array([1, 2, 3,4, 5])
n = a2.view()
n[3]=99
print(a2)
print(n)

[ 1  2  3 99  5]
[ 1  2  3 99  5]


### 重塑矩陣
- .shape
- reshape

In [45]:
import numpy as np
aa = np.array([[1,2, 3, 4],[5, 6, 7, 8]])
print(aa)
print(aa.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [44]:
aa.shape=[4,2]
print(aa)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [46]:
aa.reshape(2,4)
print(aa)

[[1 2 3 4]
 [5 6 7 8]]


In [47]:
aa.reshape(2,3)

ValueError: cannot reshape array of size 8 into shape (2,3)

### 合併陣列
`np.concatenate()`用來合併二個陣列

In [48]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print(np.concatenate([a, b]))

[1 2 3 4 5 6 7 8]


In [49]:
m1 = np.array([[1,2], [3,4]])
m2 = np.array([[3,3],[5,5]])
print(np.concatenate([m1, m2]))

[[1 2]
 [3 4]
 [3 3]
 [5 5]]


### 矩陣數學運算

In [50]:
# np.squrt(array, out=None) array 的每個元素都取平方根並回傳
m1 = np.array([[1,2], [3,4]])
out_arr = np.zeros([2,2])
x = np.sqrt(m1, out_arr)
print(x)
print(out_arr)

[[1.         1.41421356]
 [1.73205081 2.        ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [51]:
m1 = np.array([[-1,2], [3,-4]])
out_arr = np.zeros([2,2])
x = np.sqrt(m1, out_arr)
print(x)
print(out_arr)

[[       nan 1.41421356]
 [1.73205081        nan]]
[[       nan 1.41421356]
 [1.73205081        nan]]


C:\Users\User\AppData\Local\Temp\ipykernel_21992\1104922873.py:3: RuntimeWarning: invalid value encountered in sqrt
  x = np.sqrt(m1, out_arr)


In [52]:
# np.square(arr, out=None)
array1 = np.array([1, 4, 9, 16])
y = np.square(array1)
print(y)

[  1  16  81 256]


In [53]:
# np.sum(arr, axis, dtype, out)

import numpy as np
array1 = np.array([1, 2, 3, 4, 5.2])

x = np.sum(array1, dtype = np.float32)
print(x)

15.2


In [54]:
array1 = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

x = np.sum(array1, axis = 0)

print(x)

[15 18 21 24]


In [55]:
y = np.sum(array1, axis = 1)

print(y)

[10 26 42]


In [56]:
# np.power(x1, x2)

x1 = np.array([1, 2, 3, 4])

z = np.power(x1, 3)

print(z)

[ 1  8 27 64]


In [57]:
x1 = np.array([1, 2, 3, 4])
x2 = np.array([1, 2, 3, 4])
z = np.power(x1, x2)

print(z)

[  1   4  27 256]


In [58]:
array1 = np.array([[1, 2, 3, 4],
                   [6, 6, 6, 6]])
x = np.transpose(array1)

print(x)

[[1 6]
 [2 6]
 [3 6]
 [4 6]]


In [59]:
# inverse matrix

import numpy as np
a = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
print(np.linalg.inv(a))

[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


In [ ]:
# determinate of matrix
print(np.linalg.det(a))

-306.0


In [62]:
import numpy as np
from PIL import Image

x = np.linspace(0, 255, 500, dtype=np.uint8)
grad = x * np.ones((500, 1), dtype=np.uint8)

Image.fromarray(grad).show()

In [64]:
from PIL import Image
import numpy as np

# Load the image
image = Image.open('baseball1.jpg')

# Convert the image to a numpy array
image_array = np.array(image)

print(image_array.shape)

(1477, 1108, 3)


In [66]:
from PIL import Image
import numpy as np

# Load the image
image = Image.open('baseball1.jpg')

# Convert the image to a numpy array
image_array = np.array(image)

# Invert the colors
inverted_image_array = 100 - image_array

# Convert back to an image
inverted_image = Image.fromarray(inverted_image_array)

# Save or display the inverted image
inverted_image.save('baseball11.jpg')  # Save the inverted image
# inverted_image.show()  # Or display the image directly